name: Deploy Next.js Frontend

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies & Build
        run: |
          npm ci
          npm run build
        env:
          NEXT_PUBLIC_SANITY_PROJECT_ID: "w146za87"
          NEXT_PUBLIC_SANITY_DATASET: "production"

      - name: Deploy to Server via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 11092
          source: ".next,public,package.json,package-lock.json"
          target: "/www/wwwroot/cgpluxstudios.com"

      - name: Restart Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 11092
          script: |
            cd /www/wwwroot/cgpluxstudios.com
            npm ci --production
            pm2 delete cgpluxstudios-frontend cgpluxstudios || true
            pm2 start npm --name "cgpluxstudios-frontend" -- run start -- -p 3001
            pm2 save
