name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 11092
          command_timeout: 30m
          script: |
            set -e
            cd /www/wwwroot/cgpluxstudios.com
            git config --global --add safe.directory /www/wwwroot/cgpluxstudios.com
            git fetch --all
            git reset --hard origin/main
            npm install
            rm -rf .next
            npm run build
            pm2 restart cgplux-frontend --update-env || pm2 start node_modules/next/dist/bin/next --name "cgplux-frontend" -- start -p 3000
            pm2 save
